2023-10-07 22:52:31,463 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-07 22:52:31,464 - [33mPress CTRL+C to quit[0m
2023-10-07 22:52:38,548 - The cache file cache_soundcloud.json does not exist.
2023-10-07 22:52:38,549 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/eli/github/playlist_aggregator/application.py", line 57, in home
    soundcloud_data = fetch_data(SOUNDCLOUD_URL, 'retrieve_soundcloud_items', CACHED_SOUNDCLOUD_TRACKS_FILENAME)
  File "/Users/eli/github/playlist_aggregator/application.py", line 49, in fetch_data
    soup = extractor.soupify(url, True)
AttributeError: 'Extractor' object has no attribute 'soupify'
2023-10-07 22:52:38,551 - 127.0.0.1 - - [07/Oct/2023 22:52:38] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-07 22:52:39,219 - The cache file cache_soundcloud.json does not exist.
2023-10-07 22:52:39,221 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/eli/github/playlist_aggregator/application.py", line 57, in home
    soundcloud_data = fetch_data(SOUNDCLOUD_URL, 'retrieve_soundcloud_items', CACHED_SOUNDCLOUD_TRACKS_FILENAME)
  File "/Users/eli/github/playlist_aggregator/application.py", line 49, in fetch_data
    soup = extractor.soupify(url, True)
AttributeError: 'Extractor' object has no attribute 'soupify'
2023-10-07 22:52:39,223 - 127.0.0.1 - - [07/Oct/2023 22:52:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-07 22:52:39,596 - The cache file cache_soundcloud.json does not exist.
2023-10-07 22:52:39,597 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/eli/github/playlist_aggregator/application.py", line 57, in home
    soundcloud_data = fetch_data(SOUNDCLOUD_URL, 'retrieve_soundcloud_items', CACHED_SOUNDCLOUD_TRACKS_FILENAME)
  File "/Users/eli/github/playlist_aggregator/application.py", line 49, in fetch_data
    soup = extractor.soupify(url, True)
AttributeError: 'Extractor' object has no attribute 'soupify'
2023-10-07 22:52:39,599 - 127.0.0.1 - - [07/Oct/2023 22:52:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-07 22:52:39,752 - The cache file cache_soundcloud.json does not exist.
2023-10-07 22:52:39,752 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/eli/github/playlist_aggregator/application.py", line 57, in home
    soundcloud_data = fetch_data(SOUNDCLOUD_URL, 'retrieve_soundcloud_items', CACHED_SOUNDCLOUD_TRACKS_FILENAME)
  File "/Users/eli/github/playlist_aggregator/application.py", line 49, in fetch_data
    soup = extractor.soupify(url, True)
AttributeError: 'Extractor' object has no attribute 'soupify'
2023-10-07 22:52:39,754 - 127.0.0.1 - - [07/Oct/2023 22:52:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-07 22:52:54,114 - The cache file cache_soundcloud.json does not exist.
2023-10-07 22:52:54,116 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eli/github/playlist_aggregator/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/eli/github/playlist_aggregator/application.py", line 57, in home
    soundcloud_data = fetch_data(SOUNDCLOUD_URL, 'retrieve_soundcloud_items', CACHED_SOUNDCLOUD_TRACKS_FILENAME)
  File "/Users/eli/github/playlist_aggregator/application.py", line 49, in fetch_data
    soup = extractor.soupify(url, True)
AttributeError: 'Extractor' object has no attribute 'soupify'
2023-10-07 22:52:54,117 - 127.0.0.1 - - [07/Oct/2023 22:52:54] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-07 22:53:50,360 - 127.0.0.1 - - [07/Oct/2023 22:53:50] "GET / HTTP/1.1" 200 -
